### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by Wappie2000** [SteefP/myHomeBank#3]
Hi Steef,

Mockup ziet er solide uit, de implementatie van de zoekvelden is ook erg goed. Aanvinken welke zoeker je actief laat zijn neem ik aan, je kan dan ook meteen meerdere criteria aanvinken. Slim gedaan. 

Het is misschien slim om de vink automatisch aan te zetten zodra een type zoeker word gebruikt. Op die manier zie je meteen het resultaat wat je hebt met je criteria. 

Ziet er erg profi uit.

Groetjes

Bas

**Comment by SteefP** [comment]
Top, thks!

**Comment by SteefP** [comment]
Hey Bas,
De nieuwe lay-out is nu werkend. Advanced functies als direct zien welke transacties worden meegenomen is er nog niet, maar komt snel denk ik, nu de basis in place is is dat niet meer zo moeilijk.

gr Steef

**Comment by SteefP** [comment]
Ow, ja, complexe regels (meer dan critereum) en daar dan bijv 20 van maken het programma traag

**Comment by Wappie2000** [comment]
Gaan we sluiten want verleden tijd
